name: Build

# Build (creating JARs) on push, this includes building `master` and corresponding merge commits
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install pg

      - name: Initialize database
        run: node db.js

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Cache Maven local repository
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: checker
          # TODO: specify artifact name
          path: |
            target/checker-*.jar

      - name: Push to Dockerhub repository
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: dmitrykersh/checker
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}